export const adminPanel = {
  logIn: "Увійти",
  panel: "Панель керування",
  dashboard: "Головна",
  products: "Вироби",
  сollections: "Колекції",
  orders: "Замовлення",
  loggedAs: "Залогінено як",
  logout: "Вихід",
  notLoggedIn: "Не залогінено",
  brand: "mariam crochet jewelry",
  addProduct: "Додати виріб",
  addCollection: "Додати колекцію",
  newProduct: "Новий виріб",
  newCollection: "Нова колекція",
  editProduct: "Редагувати виріб",
  editCollection: "Редагувати колекцію",
  titleUk: "Заголовок UK",
  titleEn: "Заголовок EN",
  descriptionEn: "Опис UK",
  descriptionUk: "Опис EN",
  collectionName: "Назва колекції",
  coverImage: "Обкладинка",
  priceUAH: "Ціна в грн",
  requiredField: "Це поле не може бути порожнім",
  imageUrl: "Лінк на фото",
  addImageUrl: "Додати лінк на фото",
  deleteImageUrl: "Видалити лінк на фото",
  edit: "Редагувати",
  delete: "Видалити",
  save: "Зберегти",
  productNotFound: "Виріб не знайдено",
  collectionNotFound: "Колекції не знайдено",
  availability: "Статус доступності",
  withoutStatus: "Без статусу",
  inStock: "В наявності",
  preOrder: "Під замовлення",
  soldOut: "Продано",
  swalTitle: "Ви впевнені?",
  swalText: "Хочете видалити",
  swalCancelBtn: "Ні",
  swalConfirmBtn: "Так, видалити!",
  orderDate: "Дата замовлення",
  fullName: "Ім'я та прізвище",
  orderDetails: "Деталі замовлення",
  firstName: "Ім'я",
  lastName: "Прізвище",
  phoneNumber: "Номер телефону",
  messanger: "Месенджер",
  commentToOrder: "Коментар до замовлення",
  readMore: "Перегляд замовлення",
};
